/* This file is autogenerated by grm -- do not edit. */

#ifndef UNITY_INCLUDE_CONFIG_H
#error "Must define UNITY_INCLUDE_CONFIG_H."
#endif

/*** Standard includes. ***/
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>

#include "unity.h"


/*** Stuff copied from test files (should be #include's, declarations & macros only) ***/
#define SCONSOLE_WANT_INTERNAL_DEFS
#include "sconsole.h"
enum { // Error codes...
	FAULT_OK, 		// No fault.
	FAULT_MEM,		// Access out of memory space. 
	FAULT_BAD_OPCODE,	// Illegal opcode.
	FAULT_BAD_tvIP,		// tvIP outside of memory space.
	FAULT_USER		// User fault codes from here.
};

enum { // Instructions...
	OP_FAULT,	// Sets fault from next value in instruction stream.
	OP_INC,		// Increments val.
	OP_LIT,		// Loads next value in instruction stream into val.
	OP_LOAD,	// Load val from address in val.
};

/*** External test functions scraped from test files. ***/
void testHeapRamByte(sc_cell_t addr);
void testHeapRamByteBadRead();
void testHeapRamByteBadWrite();
void testHeapRamCell(sc_cell_t addr);
void testHeapRamCellBadRead();
void testHeapRamCellBadWrite();
void testInitContext(void);
void testRStackInit(void);
void testRStackSize(void);
void testRStackPopPush(void);
void testRStackReset(void);
void testRStackPeek(void);
void testRStackTosNos(void);
void testRStackCanPop(void);
void testRStackCanPush(void);
void testToyVmRunNone();
void testToyVmFaultOp();
void testToyVmInc();
void testToyVmInc2();
void testToyVmLiteral();
void testToyVmLoad();
void testToyVmLoadBad();
void testToyVmOverrun1();
void testToyVmOverrun2();
void testToyVmBadOpcode();
void testUStackInit(void);
void testUStackSize(void);
void testUStackPopPush(void);
void testUStackReset(void);
void testUStackPeek(void);
void testUStackTosNos(void);
void testUStackCanPop(void);
void testUStackCanPush(void);
void testscRunNone();
void testBadOpcode();
void testVmRunFault();
void testVmRun();
void testVmOpFault();
void testVmOpFaultFail();
void testVmUnop(uint8_t op, sc_cell_t a, sc_cell_t r);
void testBinop(uint8_t op, sc_cell_t a1, sc_cell_t a2, sc_cell_t r);
void testVmOp_FailUnderflow(uint8_t op, int n_args);
void testVmOp_FailOverflow(uint8_t op, int n_free);
void testByteLiteral();
void testCellLiteral();
void testSlashMod(sc_cell_t a1, sc_cell_t a2, sc_cell_t q, sc_cell_t r);
void testVmOpDrop();
void testVmOpDup();
void testVmOpSwap();

/*** Fixture & dump functions from test files. ***/
void ts_SetupStackTestContext(void);
void ts_DestroyStackTestContext(void);
void setupTestInitFixture(void);
void destroyTestInitFixture(void);
void vmInit(void);
void setup_test_vm(void);
void destroy_test_vm(void);

/* Declare test stubs. */
static void testHeapRamByte_stub_0(void) { testHeapRamByte(0); }
static void testHeapRamByte_stub_1(void) { testHeapRamByte(SC_HEAP_SIZE-1); }
static void testHeapRamCell_stub_2(void) { testHeapRamCell(0); }
static void testHeapRamCell_stub_3(void) { testHeapRamCell(SC_HEAP_SIZE-sizeof(sc_cell_t)); }
static void testVmUnop_stub_4(void) { testVmUnop(SC_OP_NEGATE, 0x12345678, -0x12345678); }
static void testVmOp_FailUnderflow_stub_5(void) { testVmOp_FailUnderflow(SC_OP_NEGATE, 0); }
static void testVmUnop_stub_6(void) { testVmUnop(SC_OP_ZERO_EQUALS, 0, -1); }
static void testVmUnop_stub_7(void) { testVmUnop(SC_OP_ZERO_EQUALS, -1, 0); }
static void testVmUnop_stub_8(void) { testVmUnop(SC_OP_ZERO_EQUALS, 12345, 0); }
static void testVmOp_FailUnderflow_stub_9(void) { testVmOp_FailUnderflow(SC_OP_ZERO_EQUALS, 0); }
static void testBinop_stub_10(void) { testBinop(SC_OP_MINUS, 0x12345678, -1, 0x12345679); }
static void testVmOp_FailUnderflow_stub_11(void) { testVmOp_FailUnderflow(SC_OP_MINUS, 1); }
static void testVmOp_FailUnderflow_stub_12(void) { testVmOp_FailUnderflow(SC_OP_MINUS, 0); }
static void testBinop_stub_13(void) { testBinop(SC_OP_TIMES, 1234, 5678, 1234*5678); }
static void testVmOp_FailUnderflow_stub_14(void) { testVmOp_FailUnderflow(SC_OP_TIMES, 1); }
static void testVmOp_FailUnderflow_stub_15(void) { testVmOp_FailUnderflow(SC_OP_TIMES, 0); }
static void testSlashMod_stub_16(void) { testSlashMod(38, 5, 38/5, 38%5); }
static void testVmOp_FailUnderflow_stub_17(void) { testVmOp_FailUnderflow(SC_OP_SLASH_MOD, 1); }
static void testVmOp_FailUnderflow_stub_18(void) { testVmOp_FailUnderflow(SC_OP_SLASH_MOD, 0); }
static void testVmOp_FailUnderflow_stub_19(void) { testVmOp_FailUnderflow(SC_OP_DROP, 0); }
static void testVmOp_FailUnderflow_stub_20(void) { testVmOp_FailUnderflow(SC_OP_DUP, 0); }
static void testVmOp_FailOverflow_stub_21(void) { testVmOp_FailOverflow(SC_OP_DUP, 0); }
static void testVmOp_FailUnderflow_stub_22(void) { testVmOp_FailUnderflow(SC_OP_SWAP, 0); }
static void testVmOp_FailUnderflow_stub_23(void) { testVmOp_FailUnderflow(SC_OP_SWAP, 1); }

/*** Extra Unity support. ***/

/* Functions for setup, diagnostics dump on a test failure & teardown. */
typedef void (*fixture_func_t)(void);
static fixture_func_t setUp_func, dump_func, tearDown_func;
void registerFixture(fixture_func_t setup, fixture_func_t dumper, fixture_func_t teardown) {
	setUp_func = setup;
	dump_func = dumper;
	tearDown_func = teardown;
}

void setUp() { if (setUp_func) setUp_func(); }
void dumpTestContext() { if (dump_func) dump_func(); }
void tearDown() { if (tearDown_func) tearDown_func(); }

static void do_run_test(UnityTestFunction func, const char* name, int line_num) {
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
	UnityDefaultTestRun(func, name, line_num);
}

int main(int argc, char** argv) {
/*
	int rc_parse = UnityParseOptions(argc,argv);
	if (rc_parse != 0)
		return rc_parse;
*/
  UnityBegin("");
  
  UnitySetTestFile("..\test_helpers.c");
  registerFixture(ts_SetupStackTestContext, NULL, ts_DestroyStackTestContext);
  do_run_test(testHeapRamByte_stub_0, "testHeapRamByte(0)", 23);
  do_run_test(testHeapRamByte_stub_1, "testHeapRamByte(SC_HEAP_SIZE-1)", 24);
  do_run_test(testHeapRamByteBadRead, "testHeapRamByteBadRead", 26);
  do_run_test(testHeapRamByteBadWrite, "testHeapRamByteBadWrite", 31);
  do_run_test(testHeapRamCell_stub_2, "testHeapRamCell(0)", 44);
  do_run_test(testHeapRamCell_stub_3, "testHeapRamCell(SC_HEAP_SIZE-sizeof(sc_cell_t))", 46);
  do_run_test(testHeapRamCellBadRead, "testHeapRamCellBadRead", 48);
  do_run_test(testHeapRamCellBadWrite, "testHeapRamCellBadWrite", 53);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_init.c");
  registerFixture(setupTestInitFixture, NULL, destroyTestInitFixture);
  do_run_test(testInitContext, "testInitContext", 25);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_r_stack.c");
  registerFixture(ts_SetupStackTestContext, NULL, ts_DestroyStackTestContext);
  do_run_test(testRStackInit, "testRStackInit", 14);
  do_run_test(testRStackSize, "testRStackSize", 24);
  do_run_test(testRStackPopPush, "testRStackPopPush", 28);
  do_run_test(testRStackReset, "testRStackReset", 41);
  do_run_test(testRStackPeek, "testRStackPeek", 55);
  do_run_test(testRStackTosNos, "testRStackTosNos", 63);
  do_run_test(testRStackCanPop, "testRStackCanPop", 74);
  do_run_test(testRStackCanPush, "testRStackCanPush", 98);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_toy_vm.c");
  registerFixture(vmInit, NULL, NULL);
  do_run_test(testToyVmRunNone, "testToyVmRunNone", 100);
  do_run_test(testToyVmFaultOp, "testToyVmFaultOp", 106);
  do_run_test(testToyVmInc, "testToyVmInc", 123);
  do_run_test(testToyVmInc2, "testToyVmInc2", 138);
  do_run_test(testToyVmLiteral, "testToyVmLiteral", 149);
  do_run_test(testToyVmLoad, "testToyVmLoad", 161);
  do_run_test(testToyVmLoadBad, "testToyVmLoadBad", 169);
  do_run_test(testToyVmOverrun1, "testToyVmOverrun1", 175);
  do_run_test(testToyVmOverrun2, "testToyVmOverrun2", 188);
  do_run_test(testToyVmBadOpcode, "testToyVmBadOpcode", 197);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_u_stack.c");
  registerFixture(ts_SetupStackTestContext, NULL, ts_DestroyStackTestContext);
  do_run_test(testUStackInit, "testUStackInit", 22);
  do_run_test(testUStackSize, "testUStackSize", 32);
  do_run_test(testUStackPopPush, "testUStackPopPush", 36);
  do_run_test(testUStackReset, "testUStackReset", 49);
  do_run_test(testUStackPeek, "testUStackPeek", 63);
  do_run_test(testUStackTosNos, "testUStackTosNos", 71);
  do_run_test(testUStackCanPop, "testUStackCanPop", 82);
  do_run_test(testUStackCanPush, "testUStackCanPush", 106);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_vm.c");
  registerFixture(setup_test_vm, NULL, destroy_test_vm);
  do_run_test(testscRunNone, "testscRunNone", 44);
  do_run_test(testBadOpcode, "testBadOpcode", 47);
  do_run_test(testVmRunFault, "testVmRunFault", 51);
  do_run_test(testVmRun, "testVmRun", 55);
  do_run_test(testVmOpFault, "testVmOpFault", 70);
  do_run_test(testVmOpFaultFail, "testVmOpFaultFail", 75);
  do_run_test(testByteLiteral, "testByteLiteral", 113);
  do_run_test(testCellLiteral, "testCellLiteral", 121);
  do_run_test(testVmUnop_stub_4, "testVmUnop(SC_OP_NEGATE, 0x12345678, -0x12345678)", 130);
  do_run_test(testVmOp_FailUnderflow_stub_5, "testVmOp_FailUnderflow(SC_OP_NEGATE, 0)", 131);
  do_run_test(testVmUnop_stub_6, "testVmUnop(SC_OP_ZERO_EQUALS, 0, -1)", 134);
  do_run_test(testVmUnop_stub_7, "testVmUnop(SC_OP_ZERO_EQUALS, -1, 0)", 135);
  do_run_test(testVmUnop_stub_8, "testVmUnop(SC_OP_ZERO_EQUALS, 12345, 0)", 136);
  do_run_test(testVmOp_FailUnderflow_stub_9, "testVmOp_FailUnderflow(SC_OP_ZERO_EQUALS, 0)", 137);
  do_run_test(testBinop_stub_10, "testBinop(SC_OP_MINUS, 0x12345678, -1, 0x12345679)", 140);
  do_run_test(testVmOp_FailUnderflow_stub_11, "testVmOp_FailUnderflow(SC_OP_MINUS, 1)", 141);
  do_run_test(testVmOp_FailUnderflow_stub_12, "testVmOp_FailUnderflow(SC_OP_MINUS, 0)", 142);
  do_run_test(testBinop_stub_13, "testBinop(SC_OP_TIMES, 1234, 5678, 1234*5678)", 145);
  do_run_test(testVmOp_FailUnderflow_stub_14, "testVmOp_FailUnderflow(SC_OP_TIMES, 1)", 146);
  do_run_test(testVmOp_FailUnderflow_stub_15, "testVmOp_FailUnderflow(SC_OP_TIMES, 0)", 147);
  do_run_test(testSlashMod_stub_16, "testSlashMod(38, 5, 38/5, 38%5)", 158);
  do_run_test(testVmOp_FailUnderflow_stub_17, "testVmOp_FailUnderflow(SC_OP_SLASH_MOD, 1)", 159);
  do_run_test(testVmOp_FailUnderflow_stub_18, "testVmOp_FailUnderflow(SC_OP_SLASH_MOD, 0)", 160);
  do_run_test(testVmOpDrop, "testVmOpDrop", 163);
  do_run_test(testVmOp_FailUnderflow_stub_19, "testVmOp_FailUnderflow(SC_OP_DROP, 0)", 169);
  do_run_test(testVmOpDup, "testVmOpDup", 171);
  do_run_test(testVmOp_FailUnderflow_stub_20, "testVmOp_FailUnderflow(SC_OP_DUP, 0)", 177);
  do_run_test(testVmOp_FailOverflow_stub_21, "testVmOp_FailOverflow(SC_OP_DUP, 0)", 178);
  do_run_test(testVmOpSwap, "testVmOpSwap", 180);
  do_run_test(testVmOp_FailUnderflow_stub_22, "testVmOp_FailUnderflow(SC_OP_SWAP, 0)", 187);
  do_run_test(testVmOp_FailUnderflow_stub_23, "testVmOp_FailUnderflow(SC_OP_SWAP, 1)", 188);
  registerFixture(NULL, NULL, NULL);

  return UnityEnd();
}

/*

*/
