/* This file is autogenerated by grm -- do not edit. */

#ifndef UNITY_INCLUDE_CONFIG_H
#error "Must define UNITY_INCLUDE_CONFIG_H."
#endif

/*** Standard includes. ***/
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include <stdlib.h>

#include "unity.h"


/*** Stuff copied from test files (should be #include's, declarations & macros only) ***/
enum { // Error codes...
	ERR_OK, 		// No error.
	ERR_MEM,		// access out of memory space. 
	ERR_HALT,		// HALT instruction.
	ERR_FAULT,		// FAULT instruction.
	ERR_VAL,
	ERR_BAD_OPCODE,	
	ERR_BAD_IP,		// IP outside of memory space.
	
};

enum { // Instructions...
	OP_HALT,	// Halt execution, return ERR_HALT.
	OP_FAULT,	// Generates error ERR_FAULT.
	OP_INC,		// Increments val.
	OP_X,		// Sets error ERR_VAL is val is odd, else adds 10 to it.
	OP_LIT,		// Loads next value into val, but sets error ERR_MEM if value is odd.
};

/*** External test functions scraped from test files. ***/
void testInitContext(void);
void testR_StackInit(void);
void testR_StackPopPush(void);
void testR_StackReset(void);
void testR_StackPeek(void);
void testR_StackTosNos(void);
void testR_StackCanPop(void);
void testR_StackCanPush(void);
void testR_ErrorPop(void);
void testR_ErrorPush(void);
void testR_ErrorTos(void);
void testR_ErrorNos(void);
void testR_ErrorPeek(void);
void testVmRunNone();
void testVmErrorOp(uint8_t op, uint8_t err);
void testInc();
void testInc2();
void testLiteral();
void testOverrun1();
void testOverrun2();
void testBadOpcode();
void testU_StackInit(void);
void testU_StackPopPush(void);
void testU_StackReset(void);
void testU_StackPeek(void);
void testU_StackTosNos(void);
void testU_StackCanPop(void);
void testU_StackCanPush(void);
void testU_ErrorPop(void);
void testU_ErrorPush(void);
void testU_ErrorTos(void);
void testU_ErrorNos(void);
void testU_ErrorPeek(void);

/*** Fixture & dump functions from test files. ***/
void ts_SetupStackTestContext(void);
void ts_DestroyStackTestContext(void);
void vmInit(void);

/* Declare test stubs. */
static void testVmErrorOp_stub_0(void) { testVmErrorOp(OP_HALT, ERR_HALT); }
static void testVmErrorOp_stub_1(void) { testVmErrorOp(OP_FAULT, ERR_FAULT); }

/*** Extra Unity support. ***/

/* Functions for setup, diagnostics dump on a test failure & teardown. */
typedef void (*fixture_func_t)(void);
static fixture_func_t setUp_func, dump_func, tearDown_func;
void registerFixture(fixture_func_t setup, fixture_func_t dumper, fixture_func_t teardown) {
	setUp_func = setup;
	dump_func = dumper;
	tearDown_func = teardown;
}

void setUp() { if (setUp_func) setUp_func(); }
void dumpTestContext() { if (dump_func) dump_func(); }
void tearDown() { if (tearDown_func) tearDown_func(); }

static void do_run_test(UnityTestFunction func, const char* name, int line_num) {
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
	UnityDefaultTestRun(func, name, line_num);
}

int main(int argc, char** argv) {
/*
	int rc_parse = UnityParseOptions(argc,argv);
	if (rc_parse != 0)
		return rc_parse;
*/
  UnityBegin("");
  
  UnitySetTestFile("..\test_init.c");
  registerFixture(ts_SetupStackTestContext, NULL, ts_DestroyStackTestContext);
  do_run_test(testInitContext, "testInitContext", 13);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_r_stack.c");
  registerFixture(ts_SetupStackTestContext, NULL, ts_DestroyStackTestContext);
  do_run_test(testR_StackInit, "testR_StackInit", 13);
  do_run_test(testR_StackPopPush, "testR_StackPopPush", 23);
  do_run_test(testR_StackReset, "testR_StackReset", 36);
  do_run_test(testR_StackPeek, "testR_StackPeek", 50);
  do_run_test(testR_StackTosNos, "testR_StackTosNos", 58);
  do_run_test(testR_StackCanPop, "testR_StackCanPop", 69);
  do_run_test(testR_StackCanPush, "testR_StackCanPush", 93);
  do_run_test(testR_ErrorPop, "testR_ErrorPop", 114);
  do_run_test(testR_ErrorPush, "testR_ErrorPush", 119);
  do_run_test(testR_ErrorTos, "testR_ErrorTos", 126);
  do_run_test(testR_ErrorNos, "testR_ErrorNos", 131);
  do_run_test(testR_ErrorPeek, "testR_ErrorPeek", 137);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_toy_vm.c");
  registerFixture(vmInit, NULL, NULL);
  do_run_test(testVmRunNone, "testVmRunNone", 100);
  do_run_test(testVmErrorOp_stub_0, "testVmErrorOp(OP_HALT, ERR_HALT)", 118);
  do_run_test(testVmErrorOp_stub_1, "testVmErrorOp(OP_FAULT, ERR_FAULT)", 119);
  do_run_test(testInc, "testInc", 125);
  do_run_test(testInc2, "testInc2", 140);
  do_run_test(testLiteral, "testLiteral", 152);
  do_run_test(testOverrun1, "testOverrun1", 166);
  do_run_test(testOverrun2, "testOverrun2", 179);
  do_run_test(testBadOpcode, "testBadOpcode", 188);
  registerFixture(NULL, NULL, NULL);
  
  UnitySetTestFile("..\test_u_stack.c");
  registerFixture(ts_SetupStackTestContext, NULL, ts_DestroyStackTestContext);
  do_run_test(testU_StackInit, "testU_StackInit", 13);
  do_run_test(testU_StackPopPush, "testU_StackPopPush", 23);
  do_run_test(testU_StackReset, "testU_StackReset", 36);
  do_run_test(testU_StackPeek, "testU_StackPeek", 50);
  do_run_test(testU_StackTosNos, "testU_StackTosNos", 58);
  do_run_test(testU_StackCanPop, "testU_StackCanPop", 69);
  do_run_test(testU_StackCanPush, "testU_StackCanPush", 93);
  do_run_test(testU_ErrorPop, "testU_ErrorPop", 114);
  do_run_test(testU_ErrorPush, "testU_ErrorPush", 119);
  do_run_test(testU_ErrorTos, "testU_ErrorTos", 126);
  do_run_test(testU_ErrorNos, "testU_ErrorNos", 131);
  do_run_test(testU_ErrorPeek, "testU_ErrorPeek", 137);
  registerFixture(NULL, NULL, NULL);

  return UnityEnd();
}

/*

*/
