// This file is autogenerated, do not edit.

#define SC_OPCOCODES \
	SC_OP_LIT8,  \
	SC_OP_LIT16,  \

#define SC_SNIPPETS \
	LIT8: c = CHECK_ERR(memget_char_ip()) console_u_push(c); goto next; \
	LIT16: v = CHECK_ERR(memget_cell_ip()) console_u_push(v); goto next; \

#endif
