// This file is autogenerated, do not edit.

#define SC_OPCODES \
	SC_OP_LIT8,  \
	SC_OP_LIT,  \
	SC_OP__DASH_,  \

#define SC_JUMPS \
&&lit8, &&lit, &&_dash_

#define SC_SNIPPETS \
	lit8: CHECK_FAULT(c = heap_read_byte_ip()); u_push(c); goto next; \
	lit: CHECK_FAULT(v = heap_read_cell_ip()); u_push(v); goto next; \
	_dash_: UNOP(-); goto next; \

